services:
  redis:
    image: redis:7-alpine@sha256:ff02b58f971e7d7d156a1267e283fcbbeee91773b6aa36c49dac28ecfe28eadf
    command: redis-server --appendonly yes --maxmemory 256mb --maxmemory-policy noeviction
    ports:
      - "6379:6379"
    volumes:
      - dev-redis-data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 3s
      retries: 10

volumes:
  dev-redis-data:
